language: node_js
node_js:
  - "12"
addons:
  chrome: 
    stable
dist: trusty
cache:
  yarn: true
before_install:
  - npm install -g yarn
  - yarn --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
branches:
  only:
    - master
    - test-ci
script:
  - yarn test:brave
